CREATE TABLE TB_STUDENT(
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME VARCHAR2(20) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	STD_GENDER CHAR(1),
	STD_SCORE CHAR(1)
);

ALTER TABLE TB_STUDENT
ADD CONSTRAINT STD_GENDER_CHECK
CHECK(STD_GENDER IN('M', 'F'));
ALTER TABLE TB_STUDENT
ADD CONSTRAINT STD_SCORE_CHECK
CHECK(STD_SCORE IN('A', 'B', 'C', 'D', 'F'));

CREATE SEQUENCE SEQ_STD_NO NOCACHE;

INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '짱구', 5, 'M', 'C');
INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '철수', 5, 'M', 'A');
INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '유리', 5, 'F', 'B');
INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '훈이', 5, 'M', 'C');
INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '맹구', 5, 'M', 'B');

COMMENT ON COLUMN TB_STUDENT.STD_NO IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.STD_NAME IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.STD_AGE IS '학생 나이';
COMMENT ON COLUMN TB_STUDENT.STD_GENDER IS '학생 성별';
COMMENT ON COLUMN TB_STUDENT.STD_SCORE IS '학생 성적';

SELECT * FROM TB_STUDENT;

SELECT STD_NO, STD_NAME, STD_AGE, STD_GENDER, STD_SCORE
FROM TB_STUDENT
WHERE STD_NO > 0
ORDER BY STD_NO ASC;

SELECT STD_NO, STD_NAME, STD_AGE, DECODE(STD_GENDER, 'M', '남', '여') STD_GENDER, STD_SCORE
FROM TB_STUDENT
WHERE STD_NO = 1;